# _config.yml of sacren.github.io

title: Einfach
description: The gateway to my world.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://sacren.github.io

timezone: America/Denver
encoding: utf-8

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
